### ISSUE TITLE
Make Readme.md more helpful?

### ISSUE THREAD

**Issue by vamseeachanta** [msd-prasad/PrasadMaddula-portfolio#1]
The file should be able to help get an idea of the project and what was done.
- Add more description on the objective, summary etc.
- Take a screenshot of output for the portfolio website/program and add to Readme.md?

**Comment by msd-prasad** [comment]
The **README.md file has been updated** with more description along with a screenshot of the portfolio.
Please check it out once, sir. Thank you!
